### ISSUE TITLE
Another database

### ISSUE THREAD

**Issue by camilagbm22** [usda-ars-ussl/rosetta-soil#1]
Hello!
I'm Camila, in the past few weeks I've studied Rosetta a little and I intent to make similar py library to estimate soil properties, but using database from Brazil's tropical soils. I already have the database with the parameters needed, and I wanted to know if this could be possible using your algorithm. 
Well, contact me if you have any questions and wants to colaborate with me. Thanks!
camila.melo@cropman.com.br

**Comment by thskaggs** [comment]
Hi Camila,

I responded to the email you sent. Let's discuss over email. Closing this since it is not a `rosetta-soil` issue.
